// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbckdyJLgwog1EEBw3rBN1XMHpBj55Alk',
    appId: '1:1029133785719:web:7ff2381a1a4d3e4e918472',
    messagingSenderId: '1029133785719',
    projectId: 'zaikabox-9b5f7',
    authDomain: 'zaikabox-9b5f7.firebaseapp.com',
    storageBucket: 'zaikabox-9b5f7.firebasestorage.app',
    measurementId: 'G-3PG0QTJMG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9eaK6Y1XiMzlU0roEuXbyUnqt8X1vgdY',
    appId: '1:1029133785719:android:81524df687bca55b918472',
    messagingSenderId: '1029133785719',
    projectId: 'zaikabox-9b5f7',
    storageBucket: 'zaikabox-9b5f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvAKzx4N6gieZCEGj_sUUokeRCfiFhey0',
    appId: '1:1029133785719:ios:98ace9680e1a153d918472',
    messagingSenderId: '1029133785719',
    projectId: 'zaikabox-9b5f7',
    storageBucket: 'zaikabox-9b5f7.firebasestorage.app',
    iosBundleId: 'com.example.zaikaBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvAKzx4N6gieZCEGj_sUUokeRCfiFhey0',
    appId: '1:1029133785719:ios:98ace9680e1a153d918472',
    messagingSenderId: '1029133785719',
    projectId: 'zaikabox-9b5f7',
    storageBucket: 'zaikabox-9b5f7.firebasestorage.app',
    iosBundleId: 'com.example.zaikaBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbckdyJLgwog1EEBw3rBN1XMHpBj55Alk',
    appId: '1:1029133785719:web:f0d8483ff709cfb5918472',
    messagingSenderId: '1029133785719',
    projectId: 'zaikabox-9b5f7',
    authDomain: 'zaikabox-9b5f7.firebaseapp.com',
    storageBucket: 'zaikabox-9b5f7.firebasestorage.app',
    measurementId: 'G-KSBJN86WJ7',
  );
}
